### ISSUE TITLE
KeyError: 'Payload'

### ISSUE THREAD

**Issue by Hhk78** [abdoxfox/HTTP-CUSTOM-HEADERS-VPN#46]
where am i doing wrong 
 ```
 ++++ LOGS ++++

Traceback (most recent call last):
  File "/home/h/git/HTTP-CUSTOM-HEADERS-VPN/src/ssh.py", line 152, in <module>
    start.main()
  File "/home/h/git/HTTP-CUSTOM-HEADERS-VPN/src/ssh.py", line 140, in main
    self.payload = config['Payload']['payload']
                   ~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.12/configparser.py", line 941, in __getitem__
    raise KeyError(key)
KeyError: 'Payload'
[+] KILLING PROCESS....
[+] DONE 
```
settings.ini
```
[mode]
connection_mode = 2
auto_replace = 1

[config]
payload = GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]
proxyip = 
proxyport = 

[ssh]
host = x.x.x.x
port = 22
username = test
password = *****
enable_compression = n


auth_methode = password

[sni]
server_name = api.whatsapp.com
```

**Comment by abdoxfox** [comment]
Thanks, it was fixed

**Comment by Hhk78** [comment]
> Thanks, it was fixed

this problem was solved but this problem appeared:
```
 ++++ LOGS ++++

[18:55:52] : Connected to : ('217.195.197.18', '443')
sending Payload :GET / HTTP/1.1[crlf]Host: 217.195.197.18[crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]
[18:55:52] : [Errno 104] Connection reset by peer
[+] KILLING PROCESS....
[+] DONE 
 ++++ LOGS ++++
```
I tested that stunnel works successfully on port 443.

**Comment by abdoxfox** [comment]
> > Thanks, it was fixed
> 
> this problem was solved but this problem appeared:
> 
> ```
>  ++++ LOGS ++++
> 
> [18:55:52] : Connected to : ('217.195.197.18', '443')
> sending Payload :GET / HTTP/1.1[crlf]Host: 217.195.197.18[crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]
> [18:55:52] : [Errno 104] Connection reset by peer
> [+] KILLING PROCESS....
> [+] DONE 
>  ++++ LOGS ++++
> ```
> 
> I tested that stunnel works successfully on port 443.

its about a misconfiguration in the settings file
