### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by thasunVidasara555** [abdoxfox/HTTP-CUSTOM-HEADERS-VPN#47]
++++ LOGS ++++

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    run.main()
  File "main.py", line 6, in main
    self.Tun.create_connection()
  File "/root/HTTP-CUSTOM-HEADERS-VPN/src/tunnel.py", line 114, in create_connection
    sockt.bind((localAddress,self.LISTEN_PORT))
OSError: [Errno 98] Address already in use
[06:59:52] : SNI : google.com
[06:59:52] : Connected to : ('*.*.*.*', '443')
sending Payload :
[+] KILLING PROCESS....
[+] DONE

![image](https://github.com/user-attachments/assets/b934e592-102b-4898-a224-ff4494bdf71d)

**Comment by ahmedhsin** [comment]
try
`sudo kill -9 $(ps -A | grep python | awk '{print $1}')`
after each time you run the script

**Comment by Hhk78** [comment]
this problem was solved but this problem appeared:
```
 ++++ LOGS ++++

[18:55:52] : Connected to : ('217.195.197.18', '443')
sending Payload :GET / HTTP/1.1[crlf]Host: 217.195.197.18[crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]
[18:55:52] : [Errno 104] Connection reset by peer
[+] KILLING PROCESS....
[+] DONE 
 ++++ LOGS ++++
```
I tested that stunnel works successfully on port 443.

**Comment by thasunVidasara555** [comment]
> try `sudo kill -9 $(ps -A | grep python | awk '{print $1}')` after each time you run the script
![image](https://github.com/user-attachments/assets/ade9e760-921c-4a22-a1d9-9ad9d488fb8b)
then this happens
